### ISSUE TITLE
NVDA no longer recognizes the Sonata Synth after switching to SAPI5.

### ISSUE THREAD

**Issue by mikebayus** [mush42/sonata-nvda#46]
Hello all,

Yesterday afternoon, I decided that I no longer wanted one of the third party SAPI5 synthesizers that I had installed on my PC Laptop.

As I like the Sonata TTS for NVDA Add-on that I won't ever listen to that Synth.

As it was the default Synth for my SAPI5 implementation, I thought I should chuse a different SAPI5 voice and move my SAPI5 Synth over to Microsoft.

I did that, and then I uninstalled my third party Synth.

Then, when I went in to the NVDA synth menu and picked Sonata again, I got the "Can not load Synthesizer" error.

I tried restarting NVDA, and then I tried restarting my PC, but to no avail.

Sonata would not load.

I am not sending a log file as another poster reported the same issue concerning his Eloquence Synth, and he did include two different log files.

To replicate this, just switch to SAPI5 and try to switch back again.

After about 2 hours of trying different things, I tried removing and then installing the Sonata V3.0-Beta2 add-on again and then restarting NVDA.

My Sonata voices were still there, but when I tried to launch Sonata, I found that I could not exit the NVDA settings menu, nor did I have any of the parameters for Rate Pitch etc.

All I had was and OK button.

When I pressed it, nothing happened.

I could not exit the NVDA settings menu.

I had to pick a different Synth, so I picked ESpeek and found that the menu would exit.

I removed Sonata V3.0-beta 2 and installed Sonata V3.0-beta 1 and found that everything worked.

I could load Sonata after installing the voices I had before.

I then found that I could update to V3.0-beta2 and have everything as it was.

I don't want to switch again, because I don't want to go through all that again, and because I really really like the Piper TTS voices I have.

**Comment by mikebayus** [comment]
Well, it's not only the SAPI5 synth that won't let me switch, it every other synthesizer.

In order to have my Sonata voices back after switching synths, I have to remove the add-on and the voices, then revert all the way back to the last piper version and that one is not official.

https://github.com/mush42/piper-nvda/actions/runs/8539138528/artifacts/1381177553

Then I update to V3.0 beta 1 and then update to V3.0 beta 2.

Then I have my Sonata voices back.

**Comment by mush42** [comment]
Hi @mikebayus 

This is very unexpected.

Can you provide me with the exact error message you face?

Please copy the log after a failed attempt to load the synth.

This issue, if not specific to your setup, is a priority.

Best

**Comment by mikebayus** [comment]
The error message I get is the standard "Can not load this Synthesizer.

There is on this page an issue that is the same issue concerning the
Elloquence synth.

The poster gets the same error message and has provided 2 log files.

I don't remember the number, but I think it's around issue number 44 or 45.

If I don't have too, I really don't wish to load ... say... Accapella just
so I can send you a log, but I will be most happy too if you can't find the
log files that were sent by the other poster on this issues page.

I am a church organist, and I need to spend my time preparing for the
Sunday Morning that I am required to play rather than spending the 45
minutes or so that I would need to switch synths, copy the log, remove my
sonata voices, remove the add-on, reinstall the old Piper support for NVDA
v2-24.1 add-on, then update to Sonata V3.0 beta 1, and then update to v3.0
beta 2.

I am not sure what happened to the other poster's issue, but he sent 2
different log files, if memory serves.

I think the subject line was something like "Can't load Sonata voices.

I remember going back and forth with him until at the last, he confessed
that he had Sonata working until he switched back to his Elloquence
synthesizer.

Might I suggest that you symply try loading SAPI5 and then try switching
back to Sonata?

If all goes well, it won't work, and you will get the "Can't load this
Synthesizer" error message.

 Not only that, but you will have your very own log file.

If you really need me too, I'll switch synth on purpose, and send a log.

O.K?

**Comment by mush42** [comment]
OK. I'm investigating this issue.

**Comment by mikebayus** [comment]
As I say, if you can't find the other post with the log files, or if for
some reason you are able to switch to SAPI5 and back again, let me know and
I'll send my log file.

**Comment by mikebayus** [comment]
Found it!

just in the case that you haven't located the issue that the other poster posted which I mentioned earlier in this thread, here is a link:

https://github.com/mush42/sonata-nvda/issues/42

Here are 2 really good log files that report the same issue that I have with SAPI5 and I also can't switch back after I switch to my Acapela addon.

**Comment by mush42** [comment]
@mikebayus  
Try this release:

https://github.com/mush42/sonata-nvda/releases/tag/v3.0-beta.3

**Comment by mikebayus** [comment]
Yes that worked, thank you so much.

best,
Mike

**Comment by mush42** [comment]
Great!
