### ISSUE TITLE
Sonata Neural TTS voices for NVDA have significantly different latencies when running on battery and running on AC power.

### ISSUE THREAD

**Issue by mikebayus** [mush42/sonata-nvda#51]
Hello all,

I am running the latest version of NVDA v2024.2 stable build, and I have just instaled the stable build of Sonata voices.

I have discovered that the latency of the voices is significantly higher when I run my laptop on it's battery than when I am running my laptop on AC power.

Using my stopwatch I have measured the latency of the voices on batyery as:  0.5 seconds or 500 milliseconds, and when running my laptop while plugged in to the mains, the latency is too quick for me to measure.

By no means a deal breaker, just an interesting factoid for us all to know about.

This morning, I got the bright idea to reset NVDA to disable WASAPI.

When I did that, i got the "can't load synth error".

I restored NVDA defaults, and all was well, and I got Sonata to load again.

**Comment by mush42** [comment]
Hi @mikebayus 

This is expected, since when your PC is on battery, your OS may decrease the CPU's processing speed to save power. This will be  very noticeable with Sonata, since the models are computationally intensive

Best
musharraf

**Comment by mikebayus** [comment]
Thank you so much for your prompt response.

I appreciate it.

As I say, not a dealbreaker, and I will continue to enjoy my voices.

But I am still wondering, why after I disabled WASAPI in NVDA, I could no
longer load the Somnata synth.

Eh?

Best,
Mike

**Comment by mush42** [comment]
@mikebayus 

Probably because I committed to use WASAPI specific functionality for controlling speech volume.
I'm going to change this sometime.

Best
Musharraf

**Comment by mikebayus** [comment]
Thanks Musharraf, works for me.

Best,
Mike
