### ISSUE TITLE
Unable to download voices

### ISSUE THREAD

**Issue by str20tbl** [mush42/sonata-nvda#54]
Vioces no longer download from the plugin.

![image](https://github.com/user-attachments/assets/f39ceab3-3227-475b-bb1e-82c0e074f678)

**Comment by mush42** [comment]
Please provide application logs. Voices are downloading alright in my end.

**Comment by str20tbl** [comment]
See logs attached, this is happening for me trying to download any voice but I have been trying to set up a blind user with a Welsh voice we trained and they are getting the exact same error box complaining about downloads. I have also looked for the tarball to install manually but I can't find a Welsh (cy) version in your repo.

[nvda.log](https://github.com/user-attachments/files/17241585/nvda.log)
